### ISSUE TITLE
Add shields to README

### ISSUE THREAD

**Issue by mahi-pas** [open-horizon-services/service-node-red-object-detection#2]
See https://github.com/open-horizon-services/service-homeassistant for an example of shields to add

**Comment by johnwalicki** [comment]
I also like the "Contributor" shield - example in https://github.com/open-horizon-services/service-node-red-hello-world

**Comment by oskurtt** [comment]
can I work on this one?

**Comment by johnwalicki** [comment]
Fixed by #4

**Comment by johnwalicki** [comment]
@oskurtt The issue was resolved. We reviewed the steps to fix the problem on a call with some students.
